# 32x32 Convolutional model configuration.
model:
  name: 'ConvolutionalModel'
  parameters:
    filters: 32
    kernel_size: 32
    layers: 5
    units: 600
    activation: 'tanh'
    dropout: 0
    num_pred_tones: 234
