# 8x8 Convolutional model configuration.
model:
  name: 'ConvolutionalModel'
  parameters:
    filters: 8
    kernel_size: 8
    layers: 5
    units: 600
    activation: 'tanh'
    dropout: 0
    num_pred_tones: 234
