# Default model configuration.
model:
  name: 'ConvolutionalModel'
  parameters:
    filters: 32
    kernel_size: 13
    layers: 3
    units: 256
    activation: 'tanh'
    dropout: 0
    num_pred_tones: 1
